### ISSUE TITLE
Dialog disappears after rotation

### ISSUE THREAD

**Issue by anlalalu** [brarcher/budget-watch#202]
###### Reproduction Steps

1. tap 'Budgets'
2. tap 'Select Dates'
3. rotate the screen

###### Expected Result

The dialog still exists with no error log.

###### Actual Result

The dialog disappears with the stack trace: 

E/WindowManager: android.view.WindowLeaked: Activity protect.budgetwatch.BudgetActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{52a087fc V.E..... R....... 0,0-729,1134} that was originally added here
                                                    at android.view.ViewRootImpl.<init>(ViewRootImpl.java:346)
                                                    at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:248)
                                                    at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
                                                    at android.app.Dialog.show(Dialog.java:286)
                                                    at android.app.AlertDialog$Builder.show(AlertDialog.java:951)
                                                    at protect.budgetwatch.BudgetActivity.onOptionsItemSelected(BudgetActivity.java:259)
                                                    at android.app.Activity.onMenuItemSelected(Activity.java:2600)
                                                    at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:380)
                                                    at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:195)
                                                    at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108)
                                                    at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108)
                                                    at android.support.v7.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:63)
                                                    at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:203)
                                                    at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:780)
                                                    at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
                                                    at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:171)
                                                    at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:973)
                                                    at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:963)
                                                    at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:624)
                                                    at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:150)
                                                    at android.view.View.performClick(View.java:4438)
                                                    at android.view.View$PerformClick.run(View.java:18422)
                                                    at android.os.Handler.handleCallback(Handler.java:733)
                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                    at android.os.Looper.loop(Looper.java:136)
                                                    at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                    at java.lang.reflect.Method.invokeNative(Native Method)
                                                    at java.lang.reflect.Method.invoke(Method.java:515)
                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                    at dalvik.system.NativeStart.main(Native Method)

###### Debug info
App Version = 0.21.4

Android Version = 4.4.4

Maybe can be solved with reference to this: https://stackoverflow.com/questions/2850573/activity-has-leaked-window-that-was-originally-added

**Comment by adam-poteralowicz** [comment]
I'm currently working on that.
