### ISSUE TITLE
Ask "Storage" (WRITE_EXTERNAL_STORAGE) permission before Exporting

### ISSUE THREAD

**Issue by arsadeghi** [brarcher/budget-watch#63]
Currently when the "STORAGE" permission is disabled and user clicks on "EXPORT" button, a general error message is shown ("Failed to export: /...") This message does not inform the user about the root cause of the error, which is the lack of storage permission, and cannot help him/her to find a solution for it, which is simply granting the appropriate permission. (The clip of reproducible bug scenario is attached)

![budget-watch](https://cloud.githubusercontent.com/assets/11197005/21325708/7a014280-c5dc-11e6-93a0-2bd37fe189a2.gif)

I believe the APIs for checking(checkSelfPermission)/asking(requestPermissions) STORAGE permission should get called after clicking EXPORT button.

Here is the stack trace after the error:

```
12-19 11:13:43.734 10301-13302/protect.budgetwatch E/BudgetWatch: Unable to export file
                                                                  java.io.FileNotFoundException: /storage/emulated/0/BudgetWatch.csv: open failed: EACCES (Permission denied)
                                                                      at libcore.io.IoBridge.open(IoBridge.java:452)
                                                                      at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
                                                                      at java.io.FileOutputStream.<init>(FileOutputStream.java:72)
                                                                      at protect.budgetwatch.ImportExportTask.performExport(ImportExportTask.java:85)
                                                                      at protect.budgetwatch.ImportExportTask.doInBackground(ImportExportTask.java:130)
                                                                      at protect.budgetwatch.ImportExportTask.doInBackground(ImportExportTask.java:19)
                                                                      at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                      at java.lang.Thread.run(Thread.java:818)
                                                                   Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
                                                                      at libcore.io.Posix.open(Native Method)
                                                                      at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
                                                                      at libcore.io.IoBridge.open(IoBridge.java:438)
                                                                      at java.io.FileOutputStream.<init>(FileOutputStream.java:87) 
                                                                      at java.io.FileOutputStream.<init>(FileOutputStream.java:72) 
                                                                      at protect.budgetwatch.ImportExportTask.performExport(ImportExportTask.java:85) 
                                                                      at protect.budgetwatch.ImportExportTask.doInBackground(ImportExportTask.java:130) 
                                                                      at protect.budgetwatch.ImportExportTask.doInBackground(ImportExportTask.java:19) 
                                                                      at android.os.AsyncTask$2.call(AsyncTask.java:295) 
                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                      at java.lang.Thread.run(Thread.java:818) 
```

**Comment by arsadeghi** [comment]
@brarcher Any update on this issue?

**Comment by brarcher** [comment]
Pull request https://github.com/brarcher/budget-watch/pull/64 added some improvements to the import/export activity. I did not realize it until just now, but the changes there should also help to address your concern. The activity will now request the permission when the activity is started. If the user rejects the permission, a message is shown informing the user that import/export will not work without the permission. This is not exactly what you are requesting, namely that at the moment the import/export is attempted the permission is requested. However, it is close.

Does the change mentioned above meet enough of your concern? If so, it should be resolved in the next release.

**Comment by brarcher** [comment]
Release v0.9 has been cut, and it will be available on F-Droid in a day or two. Please take a look and see if your issue is now resolved. If not, let me know.

**Comment by arsadeghi** [comment]
Perfect! Yes it will address my concern regarding to the permission issue.
Thanks for the updates @brarcher .

**Comment by brarcher** [comment]
The new release is now available. If you find the fix is not what you expected or unsatisfactory, please re-open.
